name: Inject KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y abootimg curl unzip git python3

      - name: Check boot.img exists
        run: |
          if [ ! -f input/boot.img ]; then
            echo "::error ::input/boot.img not found!"
            exit 1
          fi

      - name: Ensure mkboot is executable
        run: |
          chmod +x mkbootimg_tools/mkboot

      - name: Unpack boot.img using mkboot
        run: |
          mkdir out
          ./mkbootimg_tools/mkboot input/boot.img out

      - name: Inject KernelSU
        run: |
          KernelSU/tools/inject.sh out

      - name: Repack boot_kernelsu.img
        run: |
          ./mkbootimg_tools/mkboot out boot_kernelsu.img

      - name: Upload patched boot_kernelsu.img
        uses: actions/upload-artifact@v4
        with:
          name: boot_kernelsu
          path: boot_kernelsu.img
