name: Inject KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y abootimg curl unzip git python3

      - name: Check input/boot.img exists
        run: |
          if [ ! -f input/boot.img ]; then
            echo "::error ::input/boot.img not found!"
            exit 1
          fi

      - name: Unpack boot.img
        run: |
          cd mkbootimg_tools
          bash unpackimg.sh ../input/boot.img

      - name: Inject KernelSU
        run: |
          KernelSU/tools/inject.sh mkbootimg_tools

      - name: Repack boot_kernelsu.img
        run: |
          cd mkbootimg_tools
          bash repackimg.sh
          mv image-new.img ../boot_kernelsu.img

      - name: Upload patched boot_kernelsu.img
        uses: actions/upload-artifact@v4
        with:
          name: boot_kernelsu
          path: boot_kernelsu.img
