name: Inject KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y abootimg curl unzip git python3

      - name: Clone KernelSU and unpack tools
        run: |
          git config --global credential.helper ""
          git clone --depth=1 https://github.com/tiann/KernelSU
          git clone --depth=1 https://github.com/osm0sis/mkbootimg_tools.git
          mv mkbootimg_tools mkbootimg_tools-dir

      - name: Unpack boot.img
        run: |
          cd mkbootimg_tools-dir
          bash unpackimg.sh ../input/boot.img
          cd ..

      - name: Inject KernelSU
        run: |
          KernelSU/tools/inject.sh mkbootimg_tools-dir

      - name: Repack boot_kernelsu.img
        run: |
          cd mkbootimg_tools-dir
          bash repackimg.sh
          mv image-new.img ../boot_kernelsu.img
          cd ..

      - name: Upload boot_kernelsu.img
        uses: actions/upload-artifact@v4
        with:
          name: boot_kernelsu
          path: boot_kernelsu.img
